Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -23,6 +23,33 @@ jobs:
           docker-compose up -d
           docker exec $(docker-compose ps -q copo_web) bash -c 'ps -aef'
           docker exec $(docker-compose ps -q copo_web) bash -c 'python manage.py makemigrations && python manage.py makemigrations allauth && python manage.py migrate && python manage.py setup_sequencing_centres'
+      - run:
+          name: wait for copo_web
+          command: |
+              set -xe
+
+              wait_for_readiness() {
+                local SERVICE="$1"
+                local PORT="$2"
+                local TRY_TIMEOUT=300
+                local TRY_INTERVAL=1
+                local REMAINING_TIME=$TRY_TIMEOUT
+                while ! curl http://localhost:${PORT}/ -s -I | head -n1 | grep -q 200;
+                do
+                  REMAINING_TIME=$((REMAINING_TIME-TRY_INTERVAL))
+                  if [ $REMAINING_TIME -lt 0 ];
+                  then
+                    echo "Error: '${SERVICE}' did not start in expected duration."
+                    exit 1
+                  fi
+                  echo "Waiting for '${SERVICE}' to start... remaning ${REMAINING_TIME} seconds."
+                  sleep $TRY_INTERVAL
+                done
+                echo "The '${SERVICE}' is ready to be tested."
+              }
+  
+              wait_for_readiness  8080
+  
       - run: "curl http://127.0.0.1:8000/copo"
 
 # Orchestrate jobs using workflows
