Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -34,16 +34,17 @@ jobs:
                 local TRY_TIMEOUT=120
                 local TRY_INTERVAL=5
                 local REMAINING_TIME=$TRY_TIMEOUT
-                while ! curl http://${SERVICE}:${PORT}/ -s -I | head -n1 | grep -q 200;
+                while ! curl http://127.0.0.1:${PORT}/ -s -I | head -n1 | grep -q 200;
                 do
                   REMAINING_TIME=$((REMAINING_TIME-TRY_INTERVAL))
                   if [ $REMAINING_TIME -lt 0 ];
                   then
-                    echo "Error: '$(SERVICE)' did not start in expected duration."
+                    echo "Error: $(SERVICE) did not start in expected duration."
                     docker logs   $(docker-compose ps -q copo_web)  
+                    curl http://127.0.0.1:8000/
                     exit 1
                   fi
-                  echo "Waiting for '${SERVICE}' to start... remaning ${REMAINING_TIME} seconds."
+                  echo "Waiting for ${SERVICE} to start... remaning ${REMAINING_TIME} seconds."
                   sleep $TRY_INTERVAL
                 done
                 echo "The ${SERVICE} is ready to be tested."
